package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name = "bitacora", catalog = "panaci")
public class Bitacora implements java.io.Serializable {

	private Integer idbitacora;
	private int idusuario;
	private String fecha;
	private String accion;

	public Bitacora() {
	}

	public Bitacora(int idusuario, String fecha, String accion) {
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.accion = accion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idbitacora", unique = true, nullable = false)
	public Integer getIdbitacora() {
		return this.idbitacora;
	}

	public void setIdbitacora(Integer idbitacora) {
		this.idbitacora = idbitacora;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "fecha", nullable = false, length = 100)
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	@Column(name = "accion", nullable = false, length = 1000)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
