package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "panaci")
public class Cliente implements java.io.Serializable {

	private Integer idcliente;
	private String nombre;
	private String primerape;
	private String segunape;
	private String cedula;
	private String nacionalidad;
	private Date fechaNacii;
	private String sexo;
	private String estadoCivil;
	private byte[] imagen;
	private String ingrepor;
	private String coment;
	private Date fechaIngre;
	private String fuenteInf;
	private String estado;

	public Cliente() {
	}

	public Cliente(String nombre, String primerape, String segunape,
			String cedula, String nacionalidad, Date fechaNacii, String sexo,
			String estadoCivil, String ingrepor, Date fechaIngre,
			String fuenteInf, String estado) {
		this.nombre = nombre;
		this.primerape = primerape;
		this.segunape = segunape;
		this.cedula = cedula;
		this.nacionalidad = nacionalidad;
		this.fechaNacii = fechaNacii;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.ingrepor = ingrepor;
		this.fechaIngre = fechaIngre;
		this.fuenteInf = fuenteInf;
		this.estado = estado;
	}

	public Cliente(String nombre, String primerape, String segunape,
			String cedula, String nacionalidad, Date fechaNacii, String sexo,
			String estadoCivil, byte[] imagen, String ingrepor, String coment,
			Date fechaIngre, String fuenteInf, String estado) {
		this.nombre = nombre;
		this.primerape = primerape;
		this.segunape = segunape;
		this.cedula = cedula;
		this.nacionalidad = nacionalidad;
		this.fechaNacii = fechaNacii;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.imagen = imagen;
		this.ingrepor = ingrepor;
		this.coment = coment;
		this.fechaIngre = fechaIngre;
		this.fuenteInf = fuenteInf;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcliente", unique = true, nullable = false)
	public Integer getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "Nombre", nullable = false, length = 1000)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Primerape", nullable = false, length = 1000)
	public String getPrimerape() {
		return this.primerape;
	}

	public void setPrimerape(String primerape) {
		this.primerape = primerape;
	}

	@Column(name = "Segunape", nullable = false, length = 1000)
	public String getSegunape() {
		return this.segunape;
	}

	public void setSegunape(String segunape) {
		this.segunape = segunape;
	}

	@Column(name = "Cedula", nullable = false, length = 1000)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "Nacionalidad", nullable = false, length = 1000)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacii", nullable = false, length = 10)
	public Date getFechaNacii() {
		return this.fechaNacii;
	}

	public void setFechaNacii(Date fechaNacii) {
		this.fechaNacii = fechaNacii;
	}

	@Column(name = "Sexo", nullable = false, length = 1000)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "EstadoCivil", nullable = false, length = 1000)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "Imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@Column(name = "Ingrepor", nullable = false, length = 1000)
	public String getIngrepor() {
		return this.ingrepor;
	}

	public void setIngrepor(String ingrepor) {
		this.ingrepor = ingrepor;
	}

	@Column(name = "Coment", length = 1000)
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaIngre", nullable = false, length = 10)
	public Date getFechaIngre() {
		return this.fechaIngre;
	}

	public void setFechaIngre(Date fechaIngre) {
		this.fechaIngre = fechaIngre;
	}

	@Column(name = "FuenteInf", nullable = false, length = 1000)
	public String getFuenteInf() {
		return this.fuenteInf;
	}

	public void setFuenteInf(String fuenteInf) {
		this.fuenteInf = fuenteInf;
	}

	@Column(name = "Estado", nullable = false, length = 1000)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
