package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name = "departamentos", catalog = "panaci")
public class Departamentos implements java.io.Serializable {

	private Integer iddepart;
	private String nomdepart;
	private String descrip;

	public Departamentos() {
	}

	public Departamentos(String nomdepart, String descrip) {
		this.nomdepart = nomdepart;
		this.descrip = descrip;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iddepart", unique = true, nullable = false)
	public Integer getIddepart() {
		return this.iddepart;
	}

	public void setIddepart(Integer iddepart) {
		this.iddepart = iddepart;
	}

	@Column(name = "nomdepart", nullable = false, length = 1000)
	public String getNomdepart() {
		return this.nomdepart;
	}

	public void setNomdepart(String nomdepart) {
		this.nomdepart = nomdepart;
	}

	@Column(name = "descrip", nullable = false, length = 1000)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

}
