package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * DiagnosticoCliente generated by hbm2java
 */
@Entity
@Table(name = "diagnostico_cliente", catalog = "panaci")
public class DiagnosticoCliente implements java.io.Serializable {
	
	private int idcliente;
	private String diagnostico;
	private String nivelceguera;
	private String origenceguera;
	private String otradiscap;
	private String comentario;

	public DiagnosticoCliente() {
	}
	
	public DiagnosticoCliente(int idcliente, String diagnostico,
			String nivelceguera, String origenceguera) {
		this.idcliente = idcliente;
		this.diagnostico = diagnostico;
		this.nivelceguera = nivelceguera;
		this.origenceguera = origenceguera;
	}

	public DiagnosticoCliente(int idcliente, String diagnostico,
			String nivelceguera, String origenceguera, String otradiscap,
			String comentario) {
		this.idcliente = idcliente;
		this.diagnostico = diagnostico;
		this.nivelceguera = nivelceguera;
		this.origenceguera = origenceguera;
		this.otradiscap = otradiscap;
		this.comentario = comentario;
	}

	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "diagnostico", nullable = false, length = 1000)
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "nivelceguera", nullable = false, length = 1000)
	public String getNivelceguera() {
		return this.nivelceguera;
	}

	public void setNivelceguera(String nivelceguera) {
		this.nivelceguera = nivelceguera;
	}

	@Column(name = "origenceguera", nullable = false, length = 1000)
	public String getOrigenceguera() {
		return this.origenceguera;
	}

	public void setOrigenceguera(String origenceguera) {
		this.origenceguera = origenceguera;
	}

	@Column(name = "otradiscap", length = 1000)
	public String getOtradiscap() {
		return this.otradiscap;
	}

	public void setOtradiscap(String otradiscap) {
		this.otradiscap = otradiscap;
	}

	@Column(name = "comentario", length = 1000)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagnosticoCliente))
			return false;
		DiagnosticoCliente castOther = (DiagnosticoCliente) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& ((this.getDiagnostico() == castOther.getDiagnostico()) || (this
						.getDiagnostico() != null
						&& castOther.getDiagnostico() != null && this
						.getDiagnostico().equals(castOther.getDiagnostico())))
				&& ((this.getNivelceguera() == castOther.getNivelceguera()) || (this
						.getNivelceguera() != null
						&& castOther.getNivelceguera() != null && this
						.getNivelceguera().equals(castOther.getNivelceguera())))
				&& ((this.getOrigenceguera() == castOther.getOrigenceguera()) || (this
						.getOrigenceguera() != null
						&& castOther.getOrigenceguera() != null && this
						.getOrigenceguera()
						.equals(castOther.getOrigenceguera())))
				&& ((this.getOtradiscap() == castOther.getOtradiscap()) || (this
						.getOtradiscap() != null
						&& castOther.getOtradiscap() != null && this
						.getOtradiscap().equals(castOther.getOtradiscap())))
				&& ((this.getComentario() == castOther.getComentario()) || (this
						.getComentario() != null
						&& castOther.getComentario() != null && this
						.getComentario().equals(castOther.getComentario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37
				* result
				+ (getDiagnostico() == null ? 0 : this.getDiagnostico()
						.hashCode());
		result = 37
				* result
				+ (getNivelceguera() == null ? 0 : this.getNivelceguera()
						.hashCode());
		result = 37
				* result
				+ (getOrigenceguera() == null ? 0 : this.getOrigenceguera()
						.hashCode());
		result = 37
				* result
				+ (getOtradiscap() == null ? 0 : this.getOtradiscap()
						.hashCode());
		result = 37
				* result
				+ (getComentario() == null ? 0 : this.getComentario()
						.hashCode());
		return result;
	}

}
