package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DireccionUsuario generated by hbm2java
 */
@Entity
@Table(name = "direccion_usuario", catalog = "panaci")
public class DireccionUsuario implements java.io.Serializable {

	private DireccionUsuarioId id;

	public DireccionUsuario() {
	}

	public DireccionUsuario(DireccionUsuarioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idusuario", column = @Column(name = "idusuario", nullable = false)),
			@AttributeOverride(name = "provincia", column = @Column(name = "provincia", nullable = false, length = 1000)),
			@AttributeOverride(name = "canton", column = @Column(name = "canton", nullable = false, length = 1000)),
			@AttributeOverride(name = "distrito", column = @Column(name = "distrito", nullable = false, length = 1000)),
			@AttributeOverride(name = "otro", column = @Column(name = "otro", length = 1000)) })
	public DireccionUsuarioId getId() {
		return this.id;
	}

	public void setId(DireccionUsuarioId id) {
		this.id = id;
	}

}
