package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DirecCliente generated by hbm2java
 */
@Entity
@Table(name = "direc_cliente", catalog = "panaci")
public class DirecCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2664031101274371205L;
	
	private int idcliente;
	private String provincia;
	private String canton;
	private String distrito;
	private String otro;

	public DirecCliente() {
	}

	public DirecCliente(int idcliente, String provincia, String canton,
			String distrito, String otro) {
		this.idcliente = idcliente;
		this.provincia = provincia;
		this.canton = canton;
		this.distrito = distrito;
		this.otro = otro;
	}
	
	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "provincia", nullable = false, length = 1000)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "canton", length = 1000)
	public String getCanton() {
		return this.canton;
	}

	public void setCanton(String canton) {
		this.canton = canton;
	}

	@Column(name = "distrito", length = 1000)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "otro", length = 1000)
	public String getOtro() {
		return this.otro;
	}

	public void setOtro(String otro) {
		this.otro = otro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirecCliente))
			return false;
		DirecCliente castOther = (DirecCliente) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& ((this.getProvincia() == castOther.getProvincia()) || (this
						.getProvincia() != null
						&& castOther.getProvincia() != null && this
						.getProvincia().equals(castOther.getProvincia())))
				&& ((this.getCanton() == castOther.getCanton()) || (this
						.getCanton() != null && castOther.getCanton() != null && this
						.getCanton().equals(castOther.getCanton())))
				&& ((this.getDistrito() == castOther.getDistrito()) || (this
						.getDistrito() != null
						&& castOther.getDistrito() != null && this
						.getDistrito().equals(castOther.getDistrito())))
				&& ((this.getOtro() == castOther.getOtro()) || (this.getOtro() != null
						&& castOther.getOtro() != null && this.getOtro()
						.equals(castOther.getOtro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37 * result
				+ (getProvincia() == null ? 0 : this.getProvincia().hashCode());
		result = 37 * result
				+ (getCanton() == null ? 0 : this.getCanton().hashCode());
		result = 37 * result
				+ (getDistrito() == null ? 0 : this.getDistrito().hashCode());
		result = 37 * result
				+ (getOtro() == null ? 0 : this.getOtro().hashCode());
		return result;
	}

}
