package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name = "expediente", catalog = "panaci")
public class Expediente implements java.io.Serializable {

	private Integer idexpe;
	private int idusuario;
	private int idcliente;
	private Date fecha;
	private String descripcion;

	public Expediente() {
	}

	public Expediente(int idusuario, int idcliente, Date fecha,
			String descripcion) {
		this.idusuario = idusuario;
		this.idcliente = idcliente;
		this.fecha = fecha;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idexpe", unique = true, nullable = false)
	public Integer getIdexpe() {
		return this.idexpe;
	}

	public void setIdexpe(Integer idexpe) {
		this.idexpe = idexpe;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "descripcion", nullable = false, length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
