package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FormacionCliente generated by hbm2java
 */
@Entity
@Table(name = "formacion_cliente", catalog = "panaci")
public class FormacionCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5330252688327139251L;
	
	private int idcliente;
	private String escolaridad;
	private String ocupacion;
	private String carrera;
	private String educEspe;
	private String otros;

	public FormacionCliente() {
	}
	
	public FormacionCliente(int idcliente, String escolaridad,
			String ocupacion, String carrera, String educEspe, String otros) {
		this.idcliente = idcliente;
		this.escolaridad = escolaridad;
		this.ocupacion = ocupacion;
		this.carrera = carrera;
		this.educEspe = educEspe;
		this.otros = otros;
	}
	
	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "escolaridad", length = 1000)
	public String getEscolaridad() {
		return this.escolaridad;
	}

	public void setEscolaridad(String escolaridad) {
		this.escolaridad = escolaridad;
	}

	@Column(name = "ocupacion", length = 1000)
	public String getOcupacion() {
		return this.ocupacion;
	}

	public void setOcupacion(String ocupacion) {
		this.ocupacion = ocupacion;
	}

	@Column(name = "carrera", length = 1000)
	public String getCarrera() {
		return this.carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	@Column(name = "educ_espe", length = 1000)
	public String getEducEspe() {
		return this.educEspe;
	}

	public void setEducEspe(String educEspe) {
		this.educEspe = educEspe;
	}

	@Column(name = "otros", length = 1000)
	public String getOtros() {
		return this.otros;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormacionCliente))
			return false;
		FormacionCliente castOther = (FormacionCliente) other;

		return (this.getIdcliente() == castOther.getIdcliente())
				&& ((this.getEscolaridad() == castOther.getEscolaridad()) || (this
						.getEscolaridad() != null
						&& castOther.getEscolaridad() != null && this
						.getEscolaridad().equals(castOther.getEscolaridad())))
				&& ((this.getOcupacion() == castOther.getOcupacion()) || (this
						.getOcupacion() != null
						&& castOther.getOcupacion() != null && this
						.getOcupacion().equals(castOther.getOcupacion())))
				&& ((this.getCarrera() == castOther.getCarrera()) || (this
						.getCarrera() != null && castOther.getCarrera() != null && this
						.getCarrera().equals(castOther.getCarrera())))
				&& ((this.getEducEspe() == castOther.getEducEspe()) || (this
						.getEducEspe() != null
						&& castOther.getEducEspe() != null && this
						.getEducEspe().equals(castOther.getEducEspe())))
				&& ((this.getOtros() == castOther.getOtros()) || (this
						.getOtros() != null && castOther.getOtros() != null && this
						.getOtros().equals(castOther.getOtros())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcliente();
		result = 37
				* result
				+ (getEscolaridad() == null ? 0 : this.getEscolaridad()
						.hashCode());
		result = 37 * result
				+ (getOcupacion() == null ? 0 : this.getOcupacion().hashCode());
		result = 37 * result
				+ (getCarrera() == null ? 0 : this.getCarrera().hashCode());
		result = 37 * result
				+ (getEducEspe() == null ? 0 : this.getEducEspe().hashCode());
		result = 37 * result
				+ (getOtros() == null ? 0 : this.getOtros().hashCode());
		return result;
	}

}
