package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImagIcon generated by hbm2java
 */
@Entity
@Table(name = "imag_icon", catalog = "panaci")
public class ImagIcon implements java.io.Serializable {

	private ImagIconId id;

	public ImagIcon() {
	}

	public ImagIcon(ImagIconId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idimag", column = @Column(name = "idimag", nullable = false)),
			@AttributeOverride(name = "imagIcon", column = @Column(name = "imag_icon")) })
	public ImagIconId getId() {
		return this.id;
	}

	public void setId(ImagIconId id) {
		this.id = id;
	}

}
