package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImagIconId generated by hbm2java
 */
@Embeddable
public class ImagIconId implements java.io.Serializable {

	private int idimag;
	private byte[] imagIcon;

	public ImagIconId() {
	}

	public ImagIconId(int idimag) {
		this.idimag = idimag;
	}

	public ImagIconId(int idimag, byte[] imagIcon) {
		this.idimag = idimag;
		this.imagIcon = imagIcon;
	}

	@Column(name = "idimag", nullable = false)
	public int getIdimag() {
		return this.idimag;
	}

	public void setIdimag(int idimag) {
		this.idimag = idimag;
	}

	@Column(name = "imag_icon")
	public byte[] getImagIcon() {
		return this.imagIcon;
	}

	public void setImagIcon(byte[] imagIcon) {
		this.imagIcon = imagIcon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImagIconId))
			return false;
		ImagIconId castOther = (ImagIconId) other;

		return (this.getIdimag() == castOther.getIdimag())
				&& ((this.getImagIcon() == castOther.getImagIcon()) || (this
						.getImagIcon() != null
						&& castOther.getImagIcon() != null && Arrays.equals(
						this.getImagIcon(), castOther.getImagIcon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdimag();
		result = 37
				* result
				+ (getImagIcon() == null ? 0 : Arrays.hashCode(this
						.getImagIcon()));
		return result;
	}

}
