package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilUsuarioId generated by hbm2java
 */
@Embeddable
public class PerfilUsuarioId implements java.io.Serializable {

	private int idusuario;
	private int idperfil;
	private String usuario;
	private String pass;
	private String permisos;
	private byte[] imaperf;

	public PerfilUsuarioId() {
	}

	public PerfilUsuarioId(int idusuario, int idperfil, String usuario,
			String pass, String permisos) {
		this.idusuario = idusuario;
		this.idperfil = idperfil;
		this.usuario = usuario;
		this.pass = pass;
		this.permisos = permisos;
	}

	public PerfilUsuarioId(int idusuario, int idperfil, String usuario,
			String pass, String permisos, byte[] imaperf) {
		this.idusuario = idusuario;
		this.idperfil = idperfil;
		this.usuario = usuario;
		this.pass = pass;
		this.permisos = permisos;
		this.imaperf = imaperf;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idperfil", nullable = false)
	public int getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(int idperfil) {
		this.idperfil = idperfil;
	}

	@Column(name = "usuario", nullable = false, length = 1000)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "pass", nullable = false, length = 1000)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "permisos", nullable = false, length = 1000)
	public String getPermisos() {
		return this.permisos;
	}

	public void setPermisos(String permisos) {
		this.permisos = permisos;
	}

	@Column(name = "imaperf")
	public byte[] getImaperf() {
		return this.imaperf;
	}

	public void setImaperf(byte[] imaperf) {
		this.imaperf = imaperf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilUsuarioId))
			return false;
		PerfilUsuarioId castOther = (PerfilUsuarioId) other;

		return (this.getIdusuario() == castOther.getIdusuario())
				&& (this.getIdperfil() == castOther.getIdperfil())
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getPass() == castOther.getPass()) || (this.getPass() != null
						&& castOther.getPass() != null && this.getPass()
						.equals(castOther.getPass())))
				&& ((this.getPermisos() == castOther.getPermisos()) || (this
						.getPermisos() != null
						&& castOther.getPermisos() != null && this
						.getPermisos().equals(castOther.getPermisos())))
				&& ((this.getImaperf() == castOther.getImaperf()) || (this
						.getImaperf() != null && castOther.getImaperf() != null && Arrays
							.equals(this.getImaperf(), castOther.getImaperf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuario();
		result = 37 * result + this.getIdperfil();
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result
				+ (getPass() == null ? 0 : this.getPass().hashCode());
		result = 37 * result
				+ (getPermisos() == null ? 0 : this.getPermisos().hashCode());
		result = 37
				* result
				+ (getImaperf() == null ? 0 : Arrays
						.hashCode(this.getImaperf()));
		return result;
	}

}
