package entities;

// Generated Aug 14, 2015 11:45:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "panaci")
public class Usuarios implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	private String primerape;
	private String segunape;
	private String fechnac;
	private String nacionalidad;
	private String sexo;
	private String cedula;
	private String estadocivil;
	private byte[] imagen;
	private int iddepart;
	private String estado;

	public Usuarios() {
	}

	public Usuarios(String nombre, String primerape, String segunape,
			String fechnac, String nacionalidad, String sexo, String cedula,
			String estadocivil, int iddepart, String estado) {
		this.nombre = nombre;
		this.primerape = primerape;
		this.segunape = segunape;
		this.fechnac = fechnac;
		this.nacionalidad = nacionalidad;
		this.sexo = sexo;
		this.cedula = cedula;
		this.estadocivil = estadocivil;
		this.iddepart = iddepart;
		this.estado = estado;
	}

	public Usuarios(String nombre, String primerape, String segunape,
			String fechnac, String nacionalidad, String sexo, String cedula,
			String estadocivil, byte[] imagen, int iddepart, String estado) {
		this.nombre = nombre;
		this.primerape = primerape;
		this.segunape = segunape;
		this.fechnac = fechnac;
		this.nacionalidad = nacionalidad;
		this.sexo = sexo;
		this.cedula = cedula;
		this.estadocivil = estadocivil;
		this.imagen = imagen;
		this.iddepart = iddepart;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idusuario", unique = true, nullable = false)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "nombre", nullable = false, length = 1000)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "primerape", nullable = false, length = 1000)
	public String getPrimerape() {
		return this.primerape;
	}

	public void setPrimerape(String primerape) {
		this.primerape = primerape;
	}

	@Column(name = "segunape", nullable = false, length = 1000)
	public String getSegunape() {
		return this.segunape;
	}

	public void setSegunape(String segunape) {
		this.segunape = segunape;
	}

	@Column(name = "fechnac", nullable = false, length = 1000)
	public String getFechnac() {
		return this.fechnac;
	}

	public void setFechnac(String fechnac) {
		this.fechnac = fechnac;
	}

	@Column(name = "nacionalidad", nullable = false, length = 1000)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "sexo", nullable = false, length = 1000)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "cedula", nullable = false, length = 1000)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "estadocivil", nullable = false, length = 1000)
	public String getEstadocivil() {
		return this.estadocivil;
	}

	public void setEstadocivil(String estadocivil) {
		this.estadocivil = estadocivil;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@Column(name = "iddepart", nullable = false)
	public int getIddepart() {
		return this.iddepart;
	}

	public void setIddepart(int iddepart) {
		this.iddepart = iddepart;
	}

	@Column(name = "estado", nullable = false, length = 1000)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
